test_app:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DATA_DIR') }}/dev/output/dbt-warehouse.duckdb"
      threads: 4
    test:
      type: duckdb
      path: "{{ env_var('DATA_DIR') }}/test/output/dbt-warehouse.duckdb"
      threads: 4
